server:
  port: "8080"
  host: "0.0.0.0"

database:
  host: "db"
  port: 5432
  username: "postgres"
  password: "password"
  database: "ecommerce"
  ssl_mode: "disable"

jwt:
  secret: "docker-secret-key-change-in-production"
  expiration_hours: 24

logging:
  level: "info"
  format: "json"
